rvm:
  - 1.8.7
  - 1.9.2
  - ruby-head
  - ree
  - jruby
  - rbx
  - rbx-2.0
env:
  - "TASK=test"
  - "TASK=test TEMPLE=master"
  - "TASK=test:rails TEMPLE=master RAILS=master"
  - "TASK=test:rails RAILS=3.0.0"
script: "bundle exec rake test:ci"
